### ISSUE TITLE
nnunetv2

### ISSUE THREAD

**Issue by xintangjin** [lronkitty/SSUMamba#2]
您好，非常感谢你们开源的工作。我在安装nnunetv2出现了问题，显示我安装成功了，但我却无法import，您能提供安装细节吗？

**Comment by Sanfleeeee** [comment]
你可能安装错版本了，我安装的是nnunetv2-2.2版本的，目前可以运行代码

**Comment by AgricultureAI** [comment]
已经解决，的确是版本问题，谢谢！
