### ISSUE TITLE
icvl数据集无法实现自动下载

### ISSUE THREAD

**Issue by chunyuxiaodao** [lronkitty/SSUMamba#3]
![image](https://github.com/user-attachments/assets/54cb3a88-3f59-41fc-96ca-5b20e955a6dd)
貌似是链接失效，请问作者是否有其他下载方法

**Comment by lronkitty** [comment]
我不确定这个数据集的下载方式是否有正确的版权：
https://aistudio.baidu.com/datasetdetail/171928
https://aistudio.baidu.com/datasetdetail/171934
下载解压后目录形式如下，注意需要手动新建空文件 _.download_complete_
![1730269436477_d](https://github.com/user-attachments/assets/5002ea27-ae58-4907-994c-c7f10ebedb71)

**Comment by chunyuxiaodao** [comment]
谢谢作者的耐心解答，已解决，另外想咨询，您在4090训练一次45 epochs ，大概耗时是？

**Comment by lronkitty** [comment]
> 谢谢作者的耐心解答，已解决，另外想咨询，您在4090训练一次45 epochs ，大概耗时是？

大概一天

**Comment by chunyuxiaodao** [comment]
感谢回复
