### ISSUE TITLE
code

### ISSUE THREAD

**Issue by Johnweii25** [lronkitty/SSUMamba#5]
Hi, great work! my question is where is the sscs module in your code? and there are ssumamba_sscs.py and ssumamba.py, what's the difference?

**Comment by dw0127** [comment]
again i follow read.me pip install -e requirements/mamba, but got 'subprocess.calledprocesserror:command '['ninja','-v']' returned non-zero exut status 1.', and my torch is torch 2.1.1+cu118, the cuda version is 11.8. how to solve this?

**Comment by Johnweii25** [comment]
again i follow read.me pip install -e requirements/mamba, but got 'subprocess.calledprocesserror:command '['ninja','-v']' returned non-zero exut status 1.', and my torch is torch 2.1.1+cu118, the cuda version is 11.8. how to solve this?

**Comment by lronkitty** [comment]
> Hi, great work! my question is where is the sscs module in your code? and there are ssumamba_sscs.py and ssumamba.py, what's the difference?

Thanks for focus on my work. The ssumamba_sscs is the code with spatial–spectral continuous scan in our paper. The ssumamba is  the code without it. In our experience, the SSUMamba with SSCS show better performance in general. You can try them both.

**Comment by lronkitty** [comment]
> again i follow read.me pip install -e requirements/mamba, but got 'subprocess.calledprocesserror:command '['ninja','-v']' returned non-zero exut status 1.', and my torch is torch 2.1.1+cu118, the cuda version is 11.8. how to solve this?

Could you please tell me your operation system?

**Comment by Johnweii25** [comment]
> > again i follow read.me pip install -e requirements/mamba, but got 'subprocess.calledprocesserror:command '['ninja','-v']' returned non-zero exut status 1.', and my torch is torch 2.1.1+cu118, the cuda version is 11.8. how to solve this?
> 
> 您能告诉我您的操作系统吗？

Ubuntu 22.04.3 RTX4090 CUDA Version 12.4 python 3.10.14，i had installed cudatoolkit11.8 in virtual enviorment.

**Comment by Johnweii25** [comment]
> > again i follow read.me pip install -e requirements/mamba, but got 'subprocess.calledprocesserror:command '['ninja','-v']' returned non-zero exut status 1.', and my torch is torch 2.1.1+cu118, the cuda version is 11.8. how to solve this?
> 
> 您能告诉我您的操作系统吗？

and i pip install the mamba-ssm.whl,causal-conv1d.whl with 1.1.2 and 1.1.1 respectively.

**Comment by lronkitty** [comment]
> > > again i follow read.me pip install -e requirements/mamba, but got 'subprocess.calledprocesserror:command '['ninja','-v']' returned non-zero exut status 1.', and my torch is torch 2.1.1+cu118, the cuda version is 11.8. how to solve this?
> > 
> > 
> > 您能告诉我您的操作系统吗？
> 
> and i pip install the mamba-ssm.whl,causal-conv1d.whl with 1.1.2 and 1.1.1 respectively.

This program use the mamba-ssm and causal-conv1d from VideoMamba: https://github.com/OpenGVLab/VideoMamba, not the original mamba. So, I think you could try just use “pip install -e requirements/mamba” without install mamba-ssm.whl and causal-conv1d.whl.

**Comment by Johnweii25** [comment]
> > > > again i follow read.me pip install -e requirements/mamba, but got 'subprocess.calledprocesserror:command '['ninja','-v']' returned non-zero exut status 1.', and my torch is torch 2.1.1+cu118, the cuda version is 11.8. how to solve this?
> > > 
> > > 
> > > 您能告诉我您的操作系统吗？
> > 
> > 
> > and i pip install the mamba-ssm.whl,causal-conv1d.whl with 1.1.2 and 1.1.1 respectively.
> 
> This program use the mamba-ssm and causal-conv1d from VideoMamba: https://github.com/OpenGVLab/VideoMamba, not the original mamba. So, I think you could try just use “pip install -e requirements/mamba” without install mamba-ssm.whl and causal-conv1d.whl.

actually i had tried this, and it's working with 'Building wheel for causal_conv1d(setup.py)...'

**Comment by Johnweii25** [comment]
> > > > > again i follow read.me pip install -e requirements/mamba, but got 'subprocess.calledprocesserror:command '['ninja','-v']' returned non-zero exut status 1.', and my torch is torch 2.1.1+cu118, the cuda version is 11.8. how to solve this?
> > > > 
> > > > 
> > > > 您能告诉我您的操作系统吗？
> > > 
> > > 
> > > and i pip install the mamba-ssm.whl,causal-conv1d.whl with 1.1.2 and 1.1.1 respectively.
> > 
> > 
> > This program use the mamba-ssm and causal-conv1d from VideoMamba: https://github.com/OpenGVLab/VideoMamba, not the original mamba. So, I think you could try just use “pip install -e requirements/mamba” without install mamba-ssm.whl and causal-conv1d.whl.
> 
> actually i had tried this, and it's working with 'Building wheel for causal_conv1d(setup.py)...'

and there is another error: 'error:could not build wheels for causal_conv1d, which is required to install pyproject.toml-based projects'

**Comment by lronkitty** [comment]
> > > > > > again i follow read.me pip install -e requirements/mamba, but got 'subprocess.calledprocesserror:command '['ninja','-v']' returned non-zero exut status 1.', and my torch is torch 2.1.1+cu118, the cuda version is 11.8. how to solve this?
> > > > > 
> > > > > 
> > > > > 您能告诉我您的操作系统吗？
> > > > 
> > > > 
> > > > and i pip install the mamba-ssm.whl,causal-conv1d.whl with 1.1.2 and 1.1.1 respectively.
> > > 
> > > 
> > > This program use the mamba-ssm and causal-conv1d from VideoMamba: https://github.com/OpenGVLab/VideoMamba, not the original mamba. So, I think you could try just use “pip install -e requirements/mamba” without install mamba-ssm.whl and causal-conv1d.whl.
> > 
> > 
> > actually i had tried this, and it's working with 'Building wheel for causal_conv1d(setup.py)...'
> 
> and there is another error: 'error:could not build wheels for causal_conv1d, which is required to install pyproject.toml-based projects'

Please try this from "https://github.com/OpenGVLab/VideoMamba/blob/main/videomamba/README.md":
## Installation

- Clone this repo:

  ```shell
  git clone https://github.com/OpenGVLab/VideoMamba
  cd VideoMamba
  ```

- Create Conda environments

  ```shell
  conda create -n mamba python=3.10
  conda activate mamba
  ```


- Install PyTorch 2.1.1+cu118

  ```shell
  pip install torch==2.1.1 torchvision==0.16.1 torchaudio==2.1.1 --index-url https://download.pytorch.org/whl/cu118
  ```

- Install `causal_conv1d` and `mamba`

  ```shell
  pip install -r requirements.txt
  pip install -e causal-conv1d
  pip install -e mamba
  ```

**Comment by Johnweii25** [comment]
> > > > > > > again i follow read.me pip install -e requirements/mamba, but got 'subprocess.calledprocesserror:command '['ninja','-v']' returned non-zero exut status 1.', and my torch is torch 2.1.1+cu118, the cuda version is 11.8. how to solve this?
> > > > > > 
> > > > > > 
> > > > > > 您能告诉我您的操作系统吗？
> > > > > 
> > > > > 
> > > > > and i pip install the mamba-ssm.whl,causal-conv1d.whl with 1.1.2 and 1.1.1 respectively.
> > > > 
> > > > 
> > > > This program use the mamba-ssm and causal-conv1d from VideoMamba: https://github.com/OpenGVLab/VideoMamba, not the original mamba. So, I think you could try just use “pip install -e requirements/mamba” without install mamba-ssm.whl and causal-conv1d.whl.
> > > 
> > > 
> > > actually i had tried this, and it's working with 'Building wheel for causal_conv1d(setup.py)...'
> > 
> > 
> > and there is another error: 'error:could not build wheels for causal_conv1d, which is required to install pyproject.toml-based projects'
> 
> Please try this from "https://github.com/OpenGVLab/VideoMamba/blob/main/videomamba/README.md":
> 
> ## Installation
> * Clone this repo:
>   ```shell
>   git clone https://github.com/OpenGVLab/VideoMamba
>   cd VideoMamba
>   ```
> * Create Conda environments
>   ```shell
>   conda create -n mamba python=3.10
>   conda activate mamba
>   ```
> * Install PyTorch 2.1.1+cu118
>   ```shell
>   pip install torch==2.1.1 torchvision==0.16.1 torchaudio==2.1.1 --index-url https://download.pytorch.org/whl/cu118
>   ```
> * Install `causal_conv1d` and `mamba`
>   ```shell
>   pip install -r requirements.txt
>   pip install -e causal-conv1d
>   pip install -e mamba
>   ```

Hi, following your instructions, i had installed causal-conv1d and mamba, but in selective_scan_interface.py/import causal_conv1d_cuda import selective_scan_cuda all red, why would happen this?
